MODEL:
  META_ARCHITECTURE: "MapTextPipeline_TransformerPureDetector"
  MASK_ON: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_vitaev2_backbone"
  ViTAEv2:
    TYPE: "vitaev2_s"
    DROP_PATH_RATE: 0.3
  TRANSFORMER:
    ENABLED: True
    NUM_FEATURE_LEVELS: 4
    TEMPERATURE: 10000
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.0
    NHEADS: 8
    NUM_QUERIES: 300
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
    NUM_POINTS: 25
    INFERENCE_TH_TEST: 0.4
    VOC_SIZE: 148
    FROZEN: False

INPUT:
  FORMAT: "RGB"

DATALOADER:
  NUM_WORKERS: 8

VERSION: 2
